account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>)/', views.account_activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete/', 
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"), name='delete_confirmation'),
    
     # Wishlist
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),

    # Pending Orders
    path("pending_orders", views.pending_orders, name="pending_orders"),
    path("pending_orders/add_to_pending_orders/<int:id>", views.add_to_pending_orders, name="users_pending_orders"),
    # Contact Us/ Problemshooting
    path("contact", views.contact, name="contact"),
   
]  

checkout/urls.py
from django.urls import path
from . import views

app_name = "checkout"

urlpatterns = [
    path("deliverychoices", views.deliverychoices, name="deliverychoices"),
    path("basket_update_delivery/", views.basket_update_delivery, name="basket_update_delivery"),
    path("payment_selection/", views.payment_selection, name="payment_selection"),
    path("payment_complete/", views.payment_complete, name="payment_complete"),
    path("payment_successful/", views.payment_successful, name="payment_successful"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path("checkout/", include("checkout.urls", namespace="checkout")),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
from django.db import models
import uuid
from django.conf import settings

# Create your models here.

class DeliveryOptions(models.Model):
    """
    The Delivery methods table contining all delivery
    """

    DELIVERY_CHOICES = [

        ("DD", "Digital Delivery")
    ]

    delivery_name = models.CharField(
        verbose_name=("delivery_name"),
        help_text=("Required"),
        max_length=255,
    )
    delivery_price = models.DecimalField(
        verbose_name=("delivery price"),
        help_text=("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": ("The price must be between 0 and 999.99."),
            },
        },
        max_digits=5,
        decimal_places=2,
        default=0.00,
    )
    delivery_method = models.CharField(
        choices=DELIVERY_CHOICES,
        verbose_name=("delivery_method"),
        help_text=("Required"),
        max_length=255,
        default = False,
    )

    order = models.IntegerField(verbose_name=("list order"), help_text=("Required"), default=0)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = ("Delivery Option")
        verbose_name_plural = ("Delivery Options")

    def __str__(self):
        return self.delivery_name

class PaymentSelections(models.Model):
    """
    Store payment options
    """

    name = models.CharField(
        verbose_name=("name"),
        help_text=("Required"),
        max_length=255,
    )

    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = ("Payment Selection")
        verbose_name_plural = ("Payment Selections")

    def __str__(self):
        return self.name
    
class MockOrder(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    
    
    

checkout/views.py
from django.shortcuts import render

import json

from basket.basket import Basket
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from orders.models import *
from checkout.models import *

from .models import DeliveryOptions
from paypalcheckoutsdk.orders import OrdersGetRequest

from .paypal import PayPalClient


@login_required
def deliverychoices(request):
    deliveryoptions = DeliveryOptions.objects.filter(is_active=True)
    return render(request, "checkout/delivery_choices.html", {"deliveryoptions": deliveryoptions})

@login_required
def basket_update_delivery(request):
    basket = Basket(request)
    if request.POST.get("action") == "post":
        delivery_option = int(request.POST.get("deliveryoption"))
        delivery_type = DeliveryOptions.objects.get(id=delivery_option)
        updated_total_price = basket.basket_update_delivery(delivery_type.delivery_price)

        session = request.session
        if "purchase" not in request.session:
            session["purchase"] = {
                "delivery_id": delivery_type.id,
            }
        else:
            session["purchase"]["delivery_id"] = delivery_type.id
            session.modified = True

        response = JsonResponse({"total": updated_total_price, "delivery_price": delivery_type.delivery_price})
        return response


@login_required
def payment_selection(request):
    print('Create order_id')
    mockorder = MockOrder()
    mockorder.save()
    session = request.session
    '''if "delivery_id" not in request.session:
        messages.success(request, "Please select delivery option")
        return HttpResponseRedirect(request.META["HTTP_REFERER"])'''
    
    return render(request, "checkout/payment_selection.html", {})



####
# PayPay
####


@login_required
def payment_complete(request):
    PPClient = PayPalClient()

    body = json.loads(request.body)
    data = body["orderID"]
    user_id = request.user.id

    requestorder = OrdersGetRequest(data)
    response = PPClient.client.execute(requestorder)

    total_paid = response.result.purchase_units[0].amount.value
    print('Found')

    basket = Basket(request)
    order = Order.objects.create(
        user_id=user_id,
        full_name=response.result.purchase_units[0].shipping.name.full_name,
        email=response.result.payer.email_address,
        total_paid=response.result.purchase_units[0].amount.value,
        order_key=response.result.id,
        payment_option="paypal",
        billing_status=True,
    )
    order_id = order.pk

    for item in basket:
        OrderItem.objects.create(order_id=order_id, product=item["product"], price=item["price"], quantity=item["qty"])

    return JsonResponse("Payment completed!", safe=False)

@login_required
def payment_successful(request):
    session = request.session
    return render(request, "checkout/payment_successful.html", {})

templates/checkout/delivery_choices.html
{% extends "../store/base.html" %}
{% load static %}
{% block title %}Delivery Options{%endblock %}
{% block content %}

<main class="pt-5">
  <div class="container" style="max-width: 1000px">
    <div class="col-12">
      <h1 class="h2"> Delivery Options <b>{{user.user_name}}</b></h1>
    </div>
    <div class="col-12 d-flex justify-content-between">
    <p>Select your payment options</p>
  </div>
  <hr />
</div>


<div class="container">
{% if messages %}
<div class="alert alert-warning" alert-{{ message.tags }} role="alert">
  {% for message in messages  %}
    {{message|safe}}
  {% endfor %}
</div>
{% endif %}
  <div class="row g-3">
    
    <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
      <div class="d-flex bd-highlight ms-0">
        <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">€</span><span id="sub_total"
            class="fw-bold h5">{{basket.get_subtotal_price}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">€</span><span id="delivery_price"
            class="fw-bold h5">{{basket.get_delivery_price}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">€</span><span id="total"
            class="fw-bold h5">{{basket.get_total_price}}</span></div>
      </div>
      <a role="button" href="{% url 'checkout:payment_selection' %}" class="btn btn-success fw-bold w-100"
        type="button">Pay Securely</a>
    </div>
    <div class="col-md-7 col-lg-8">
      {% for option in deliveryoptions %}
      <div class="card mb-3 border-1 rounded-0 product-item me-md-4" data-index="{{option.id}}">
        <div class="row g-0">
          <div class="col-md-2 ps-3 ps-md-4">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-truck mt-2"
              viewBox="0 0 16 16">
              <path
                d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
            </svg>
          </div>
          <div class="col-md-9 ps-md-1">
            <div class="card-body p-1">
              <p class="card-text ps-2 mb-1 pt-1 fw-bold">{{option.delivery_name}}</p>
              <p>Find your ebook in your email address immediately and with no hustle. Free of charge!</p>
            </div>
          </div>
          <div class="col-md-1 ps-md-1">
            <input class="align-middle h-100" type="radio" name="deliveryOption" id="{{option.id}}"
              value="{{option.id}}">
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  
  </div>
</div>

</main>
{% endblock %}

templates/checkout/payment_selection.html
{% extends "../store/base.html" %}
{% load static %}
{% block title %}Payment Selection{%endblock %}
{% block content %}

<div class="container">
    <div class="col-12">
        <h1 class="h2">Delivery Options</h1>
    </div>
    <div class="col-12">
        <p>Please select your delivery option</p>
    </div>
    <hr />
</div>

<div class="container">
    <div class="row g-3">
        <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
            <div class="d-flex bd-highlight ms-0">
                <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>
                <div class="p-2 bd-highlight"><span class="fw-bold h5">€</span><span id="sub_total"
                        class="fw-bold h5">{{basket.get_subtotal_price}}</span></div>
            </div>
            <div class="d-flex bd-highlight">
                <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
                <div class="p-2 bd-highlight"><span class="fw-bold h5">€</span><span id="delivery_price"
                        class="fw-bold h5">{{basket.get_delivery_price}}</span></div>
            </div>
            <div class="d-flex bd-highlight">
                <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
                <div class="p-2 bd-highlight"><span class="fw-bold h5">€</span><span id="total"
                        class="fw-bold h5">{{basket.get_total_price}}</span></div>
            </div>
        </div>
        <div class="col-md-7 col-lg-8 pe-0 pe-md-5">
            <div id="paypal-button-container"></div>
        </div>
    </div>
</div>
<script
    src="https://www.paypal.com/sdk/js?client-id=AQ1GfPGZM5WmGULqn4GEQa1tJa7mIrg457VxYeSBLZIfS6-PdqP2O_L3AjiJ5-zoGf-UPeV6vrn8b5qE&currency=EUR"
    data-sdk-integration-source="button-factory">
    </script>
<script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

    function initPayPalButton() {
        paypal.Buttons({
            style: {
                shape: 'rect',
                color: 'gold',
                layout: 'vertical',
                label: 'paypal',

            },
            createOrder: function (data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        "amount": {
                            "currency_code": "EUR",
                            "value": '{{basket.get_total_price}}'
                        }
                    }]
                });
            },
            onApprove: function (data) {
                var url = "{% url 'checkout:payment_successful' %}"
                return fetch(url, {
                    method: 'POST',
                    headers: {
                        'content-type': 'application/json',
                        'X-CSRFToken': csrftoken,
                    },
                    body: JSON.stringify({
                        orderID: data.orderID
                    })
                }).then(function () {
                    location.href = "{% url 'checkout:payment_successful' %}";
                })
            },
        }).render('#paypal-button-container');
    }
    initPayPalButton();

</script>

{% endblock %}

templates/checkout/payment_successful.html
{% extends "../store/base.html" %}
{% load static %}
{% block title %}Payment Successful{%endblock %}
{% block content %}
<style type="text/css">

  body
  {
      background:#f2f2f2;
  }

  .payment
{
  border:1px solid #f2f2f2;
  height:280px;
      border-radius:20px;
      background:#fff;
}
 .payment_header
 {
   background:green;
   padding:20px;
   border-radius:20px 20px 0px 0px;
   
 }
 
 .check
 {
   margin:0px auto;
   width:50px;
   height:50px;
   border-radius:100%;
   background:#fff;
   text-align:center;
 }
 .check i
 {
   vertical-align:middle;
   line-height:50px;
   font-size:30px;
 }
  .content 
  {
      text-align:center;
  }

  .content  h1
  {
      font-size:25px;
      padding-top:25px;
  }

  .content a
  {
      width:200px;
      height:35px;
      color:#fff;
      border-radius:30px;
      padding:5px 10px;
      background:green;
      transition:all ease-in-out 0.3s;
  }

  .content a:hover
  {
      text-decoration:none;
      background:lime;

 
  }
 
</style>
<div class="container">
  <div class="row">
     <div class="col-md-6 mx-auto mt-5">
        <div class="payment">
           <div class="payment_header">
            
              <div class="check"><i class="fa fa-check" aria-hidden="true"></i></div>
           
           </div>
           <div class="content">
              <h1>Payment Successful !</h1>
              <p>Your order will be in your email shortly. Happy readings! </p>
              <a href="{% url "account:dashboard" %}">Back to Dashboard</a>
           </div>
           
        </div>
     </div>
  </div>
</div>


{% endblock %}
{% block footer %}
<div class="jumbotron jumbotron-fluid bg-dark p-4 mt-5 mb-0" style = "position: fixed;height: 100px;bottom: 0;width: 100%;">
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4 cizgi">
                <div class="card bg-dark border-0">
                    <div class="card-body text-light text-center">
                        <h5 class="card-title text-white display-4" style="font-size:20px">BookStore</h5>
                    <p class="d-inline lead">Team Les Miserables © 2022<br>
                    <a href="#" class="text-light d-block lead">Blog</a>
                    </p>

                    </div>
                </div>
            </div>
            
            <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 cizgi">
                <div class="card bg-dark border-0">
                    <div class="card-body text-center">
                        <h5 class="card-title text-white display-4" style="font-size:20px">Contact Us</h5>
                        <a class="text-light d-block lead" style="margin-left: -20px" href="#"><i class="fa fa-phone mr-2"></i>+90 (123) 456 7 899</a>
                        <a class="text-light d-block lead" href="#"><i class="fa fa-envelope mr-2"></i>admin@localhost.com</a>
                    </div>
                </div>
            </div>
            
            <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
                <div class="card bg-dark border-0">
                    <div class="card-body text-center">
                    <h5 class="card-title text-white display-4" style="font-size:20px">Social Media</h5>
            
                            <a class="text-light" href="#"><i class="fa fa-facebook-square fa-fw fa-2x"></i></a>
                        
                            <a class="text-light" href="#"><i class="fa fa-twitter-square fa-fw fa-2x"></i></a>
                        
                            <a class="text-light" href="#"><i class="fa fa-instagram fa-fw fa-2x"></i></a>
                        
                            <a class="text-light" href="#"><i class="fa fa-linkedin fa-fw fa-2x"></i></a>
                        
                    </div>
                </div>
            </div>	
        </div>
    </div>
</div>
{% endblock %}