account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>)/', views.account_activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete/', 
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"), name='delete_confirmation'),
    
     # Wishlist
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),

    # Pending Orders
    path("pending_orders", views.pending_orders, name="pending_orders"),
    path("pending_orders/add_to_pending_orders/<int:id>", views.add_to_pending_orders, name="users_pending_orders"),
    # Contact Us/ Problemshooting
    path("contact", views.contact, name="contact"),
   
]  

basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path("checkout/", include("checkout.urls", namespace="checkout")),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path, include

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from isbn_field import ISBNField


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    dirty_isbn = ISBNField(clean_isbn=False)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.png')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    is_active = models.BooleanField(default=True)
    new_arrival = models.BooleanField(default=True)
    users_wishlist = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_wishlist", blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    users_pending_orders = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_pending_orders", blank=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product
from quoteapi.views import *
import requests

def product_all(request):
        response = requests.request("GET", url, headers=headers).json()
        formatted_quote_content = response['content']
        formatted_quote_originator = response['originator']['name']
        formatted_quote = f'"{formatted_quote_content}" - by {formatted_quote_originator}'
        products = Product.products.all()
        return render(request, 'store/home.html',{'response':formatted_quote,'products': products})


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    return render(request, 'store/products/single.html', {'product': product})

templates/store/products/category.html
{% extends "../base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<style>
#cardsize{
  transition-transform: 0.4s;
 
  
}
#cardsize:hover{
  transform: scale(1.2);
}
</style>
<main>
  <div class="container">
    <div class="row">
      <div class="album py-5">


        <div class="pb-3"><h1 class="h3">All in <b>{{category.name}}</b></h1></div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

          {% for product in products %}

          <div class="col" id="cardsize">
            <div class="card border-0" style="margin-top:20px; margin-bottom:40px;">
              <img class="img-fluid" style= "height: 300px;" alt="Responsive image" src="{{ product.image.url }}">
              <div class="card-body px-0">
                <p class="card-text">
                  <a class="text-dark text-decoration-none" 
                    href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </p>
                <div class="d-flex justify-content-between align-items-center" style="height: 60px; margin-left:10px;">
                  <!--<small class="text-muted">€{{product.price}}</small>-->
                </div>
              </div>
            </div>
          </div>

          {% endfor %}

        </div>
      </div>
    </div>

  </div>


</main>

{% endblock %}

templates/store/products/single.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
<div class="pb-3"><h1 class="h3">{{ product.name }}</h1></div>
{% endblock %}
{% block content %}


<main class="pt-2">

    <div class="container" style="max-width: 1000px">

        {% if messages %}
        <div class="alert alert-warning" alert-"{{ message.tags }}" role="alert">
            {% for message in messages %}
            {{message|safe}} - <a href="{% url 'account:wishlist' %}" class="alert-link">Your Wishlist</a>
            {% endfor %}
        </div>
        {% endif %}
    
        <div class="row g-3">
          
            <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
                <div class="d-grid gap-2">
                    
                    <div><span class="h3">€{{ product.price }}</span>
                        <p class="text-muted">Ebook</p>
                    </div>
               
                    <div class="">
                        <label for="select">Qty</label>
                        <select id="select" class="h6" style="width:50px;height:40px;">
                            <option value="0">0</option>
                            <option value="1">1</option>
                        </select>
                        <div><textarea readonly class="form-control" id="exampleFormControlTextarea3"
                                rows="7">{{ product.description }}</textarea></div>
                    </div>
                    <hr>
                    <button type="button" id="add-button" value="{{product.id}}" class="btn btn-success fw500">Add to
                        basket</button>
                        <a href="{% url 'account:user_wishlist' product.id  %}" class="btn btn-light fw500" role="button" aria-disabled="true" id="add-button2" >Add to Favorites</a>
                    <hr>
                </div>
            </div>

            <div class="col-md-7 col-lg-7 p-0">
                <div class="card mb-3 border-0">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-body p-1">
                                <h1 class="mb-0 h2 pe-4 pb-4">{{ product.title }}</h1>
                                <div class="bg-light"><img class="img-fluid mx-auto d-block img-thumbnail" width="200px"
                                        alt="Responsive image" src="{{ product.image.url }}"> </div>
                            </div>
                        </div>
                    </div>
                </div>



            </div>

        </div>
    </div>
</main>

<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) { }
        });
    })
</script>

{% block footer %}
<div class= "jumbotron jumbotron-fluid bg-dark p-4 mt-5 mb-0" style = "position: fixed;height: 100px;bottom: 0;width: 100%;">
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4 cizgi">
                <div class="card bg-dark border-0">
                    <div class="card-body text-light text-center">
                        <h5 class="card-title text-white display-4" style="font-size:20px">BookStore</h5>
                    <p class="d-inline lead">Team Les Miserables © 2022<br>
                    <a href="#" class="text-light d-block lead">Blog</a>
                    </p>

                    </div>
                </div>
            </div>
            
            <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 cizgi">
                <div class="card bg-dark border-0">
                    <div class="card-body text-center">
                        <h5 class="card-title text-white display-4" style="font-size:20px">Contact Us</h5>
                        <a class="text-light d-block lead" style="margin-left: -20px" href="#"><i class="fa fa-phone mr-2"></i>+90 (123) 456 7 899</a>
                        <a class="text-light d-block lead" href="#"><i class="fa fa-envelope mr-2"></i>admin@localhost.com</a>
                    </div>
                </div>
            </div>
            
            <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
                <div class="card bg-dark border-0">
                    <div class="card-body text-center">
                    <h5 class="card-title text-white display-4" style="font-size:20px">Social Media</h5>
            
                            <a class="text-light" href="#"><i class="fa fa-facebook-square fa-fw fa-2x"></i></a>
                        
                            <a class="text-light" href="#"><i class="fa fa-twitter-square fa-fw fa-2x"></i></a>
                        
                            <a class="text-light" href="#"><i class="fa fa-instagram fa-fw fa-2x"></i></a>
                        
                            <a class="text-light" href="#"><i class="fa fa-linkedin fa-fw fa-2x"></i></a>
                        
                    </div>
                </div>
            </div>	
        </div>
    </div>
</div>
{% endblock %}
{% endblock %}